name: Build and Deploy app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app repository
        uses: actions/checkout@v3

      - name: Set commit SHA
        id: vars
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          SHORT_SHA=${{ steps.vars.outputs.SHORT_SHA }}
          docker build -t ecommerce-site:${SHORT_SHA} -f Dockerfile .
          docker tag ecommerce-site:${SHORT_SHA} ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-site:${SHORT_SHA}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-site:${SHORT_SHA}
          echo "IMAGE_TAG=${SHORT_SHA}" >> $GITHUB_ENV

      - name: Checkout Helm repository
        uses: actions/checkout@v3
        with:
          repository: nixhal33/kubernetes
          token: ${{ secrets.GH_PAT }}
          path: kubernetes

      - name: Update image tag
        run: |
          FILE="kubernetes/helm/ecommerce-site/values.yaml"
          sed -i "s/tag:.*/tag: \"${IMAGE_TAG}\"/" $FILE
          echo "Updated values.yaml with tag: ${IMAGE_TAG}"
          cat $FILE

      - name: Commit and push changes
        run: |
          cd kubernetes
          git config --global user.email "nischal.koirala33@gmail.com"
          git config --global user.name "nixhal33"
          git add .
          git commit -m "Update image to tag ${IMAGE_TAG}"
          git push